In [1]:
import numpy as np
import pandas as pd

In [2]:
data_path = 'UltimateDataset/result1124.csv'

In [3]:
data = pd.read_csv(data_path)

In [6]:
data.describe()

,QuestionId,Score,AnswerCount,ViewCount,FavoriteCount,LastEditorUserId,RealReputation,QuestionerId,QuestionerQuestionCount,TimeWaited,AcceptedState,TitleVerbCount,Unnamed: 21,Unnamed: 22,Unnamed: 23
count,4.067800e+04,40678.000000,40678.000000,40678.000000,6072.000000,2.213700e+04,40678.000000,4.067800e+04,40678.000000,4.067800e+04,40678.000000,40678.000000,0.0,22.000000,2.0
mean,4.592335e+07,0.680859,0.974507,657.345346,1.177866,3.789548e+06,1782.004695,5.024898e+06,44.240892,-3.348059e+05,0.018093,1.349526,NaN,48.681818,11.0
std,7.369567e+06,2.935578,0.977241,2536.479541,2.134418,2.985635e+06,9982.175916,2.802793e+06,112.267620,4.839012e+05,0.133291,1.119135,NaN,81.890977,0.0
min,3.279480e+07,-23.000000,0.000000,6.000000,0.000000,-1.000000e+00,-1.000000,1.120000e+02,1.000000,-1.047782e+06,0.000000,0.000000,NaN,1.000000,11.0
25%,4.067657e+07,0.000000,0.000000,60.000000,1.000000,1.037747e+06,26.000000,2.559140e+06,3.000000,-1.024620e+06,0.000000,1.000000,NaN,1.000000,11.0
50%,4.850571e+07,0.000000,1.000000,172.000000,1.000000,3.337752e+06,146.000000,5.226560e+06,10.000000,2.419444e-01,0.000000,1.000000,NaN,16.000000,11.0
75%,4.901765e+07,1.000000,1.000000,548.000000,1.000000,6.136999e+06,884.000000,7.185213e+06,35.000000,3.917847e+00,0.000000,2.000000,NaN,62.250000,11.0
max,5.699102e+07,192.000000,17.000000,161579.000000,110.000000,1.387436e+07,881548.000000,9.999799e+06,2306.000000,4.241350e+04,1.000000,10.000000,NaN,350.000000,11.0